#pragma once
// GENERATED FILE -- do not hand-edit. Regenerate with
// tools/generate_factory_presets_header.py after changing
// Source/Presets/Factory/*.xml.
#include "audioplugins/common/presets/Preset.h"
#include <vector>

inline std::vector<audioplugins::common::presets::Preset> arcanistFactoryPresets()
{
    using audioplugins::common::presets::Preset;
    using audioplugins::common::presets::ParameterValue;
    std::vector<Preset> presets;
    {
        Preset p;
        p.name = "Celestial Drift";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 0.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 5.0f},
            {"filter_cutoff", 6000.0f},
            {"filter_resonance", 0.3f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.5f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.7f},
            {"env_release", 4.0f},
            {"env_filter_mod", 20.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 30.0f},
            {"lfo_target", 0.0f},
            {"output_gain", 0.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 20.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Heavenly Glow";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 0.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 8.0f},
            {"filter_cutoff", 5500.0f},
            {"filter_resonance", 0.2f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.8f},
            {"env_decay", 2.0f},
            {"env_sustain", 0.75f},
            {"env_release", 5.0f},
            {"env_filter_mod", 15.0f},
            {"lfo_speed", 0.25f},
            {"lfo_depth", 20.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 0.0f},
            {"osc2_phase", 90.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 22.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Cloud Nine";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", -3.0f},
            {"osc_detune", 12.0f},
            {"filter_cutoff", 4500.0f},
            {"filter_resonance", 0.4f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.0f},
            {"env_decay", 2.5f},
            {"env_sustain", 0.8f},
            {"env_release", 5.5f},
            {"env_filter_mod", 30.0f},
            {"lfo_speed", 0.2f},
            {"lfo_depth", 40.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 18.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 5500.0f},
            {"osc2_flt_reso", 0.15f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Starlight";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 0.0f},
            {"osc_tune", 3.0f},
            {"osc_detune", 3.0f},
            {"filter_cutoff", 7000.0f},
            {"filter_resonance", 0.5f},
            {"filter_mode", 1.0f},
            {"env_attack", 0.3f},
            {"env_decay", 1.0f},
            {"env_sustain", 0.7f},
            {"env_release", 4.0f},
            {"env_filter_mod", 25.0f},
            {"lfo_speed", 0.4f},
            {"lfo_depth", 50.0f},
            {"lfo_target", 0.0f},
            {"output_gain", 2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 3.0f},
            {"osc2_mix_depth", 100.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Nebula";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", -6.0f},
            {"osc_detune", 15.0f},
            {"filter_cutoff", 3500.0f},
            {"filter_resonance", 0.2f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.2f},
            {"env_decay", 3.0f},
            {"env_sustain", 0.6f},
            {"env_release", 6.0f},
            {"env_filter_mod", 10.0f},
            {"lfo_speed", 0.15f},
            {"lfo_depth", 35.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 10.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 600.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Infinite Space";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 0.0f},
            {"osc_tune", -9.0f},
            {"osc_detune", 20.0f},
            {"filter_cutoff", 3000.0f},
            {"filter_resonance", 0.1f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.5f},
            {"env_decay", 3.5f},
            {"env_sustain", 0.5f},
            {"env_release", 7.0f},
            {"env_filter_mod", 5.0f},
            {"lfo_speed", 0.1f},
            {"lfo_depth", 25.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -6.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 0.0f},
            {"osc2_phase", 180.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 18.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Midnight Cathedral";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", -12.0f},
            {"osc_detune", 10.0f},
            {"filter_cutoff", 2500.0f},
            {"filter_resonance", 0.6f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.2f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.7f},
            {"env_release", 5.0f},
            {"env_filter_mod", 40.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 20.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 120.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 28.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Ominous Swell";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", -8.0f},
            {"osc_detune", 12.0f},
            {"filter_cutoff", 2800.0f},
            {"filter_resonance", 0.75f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.4f},
            {"env_decay", 2.0f},
            {"env_sustain", 0.8f},
            {"env_release", 6.0f},
            {"env_filter_mod", 50.0f},
            {"lfo_speed", 0.2f},
            {"lfo_depth", 30.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 0.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 38.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.6f},
            {"osc2_env_decay", 2.0f},
            {"osc2_env_sustain", 0.7f},
            {"osc2_env_release", 5.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Cinematic Strings";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", -3.0f},
            {"osc_detune", 8.0f},
            {"filter_cutoff", 4000.0f},
            {"filter_resonance", 0.4f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.3f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.75f},
            {"env_release", 4.5f},
            {"env_filter_mod", 25.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 25.0f},
            {"lfo_target", 2.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 35.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Deep Mystery";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", -15.0f},
            {"osc_detune", 5.0f},
            {"filter_cutoff", 2200.0f},
            {"filter_resonance", 0.5f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.8f},
            {"env_decay", 2.5f},
            {"env_sustain", 0.6f},
            {"env_release", 5.5f},
            {"env_filter_mod", 35.0f},
            {"lfo_speed", 0.25f},
            {"lfo_depth", 15.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 45.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 12.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Shadowed Dream";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", -6.0f},
            {"osc_detune", 18.0f},
            {"filter_cutoff", 3200.0f},
            {"filter_resonance", 0.3f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.0f},
            {"env_decay", 2.5f},
            {"env_sustain", 0.5f},
            {"env_release", 5.0f},
            {"env_filter_mod", 20.0f},
            {"lfo_speed", 0.2f},
            {"lfo_depth", 20.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -5.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 18.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 4500.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Rich Strings";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 10.0f},
            {"filter_cutoff", 4500.0f},
            {"filter_resonance", 0.35f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.4f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.8f},
            {"env_release", 4.5f},
            {"env_filter_mod", 20.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 20.0f},
            {"lfo_target", 2.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 0.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 32.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Velvet Warmth";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", 2.0f},
            {"osc_detune", 12.0f},
            {"filter_cutoff", 5000.0f},
            {"filter_resonance", 0.25f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.6f},
            {"env_decay", 2.0f},
            {"env_sustain", 0.85f},
            {"env_release", 5.0f},
            {"env_filter_mod", 15.0f},
            {"lfo_speed", 0.25f},
            {"lfo_depth", 15.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 90.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 28.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Choir Shimmer";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", -2.0f},
            {"osc_detune", 15.0f},
            {"filter_cutoff", 5500.0f},
            {"filter_resonance", 0.3f},
            {"filter_mode", 1.0f},
            {"env_attack", 0.7f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.8f},
            {"env_release", 4.5f},
            {"env_filter_mod", 25.0f},
            {"lfo_speed", 0.35f},
            {"lfo_depth", 35.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 1.0f},
            {"osc2_mix_depth", 35.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 5000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Golden Hour";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", 5.0f},
            {"osc_detune", 8.0f},
            {"filter_cutoff", 4800.0f},
            {"filter_resonance", 0.2f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.5f},
            {"env_decay", 1.8f},
            {"env_sustain", 0.8f},
            {"env_release", 4.0f},
            {"env_filter_mod", 18.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 25.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 0.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 22.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Organic Bloom";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", -1.0f},
            {"osc_detune", 18.0f},
            {"filter_cutoff", 4200.0f},
            {"filter_resonance", 0.4f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.8f},
            {"env_decay", 2.0f},
            {"env_sustain", 0.75f},
            {"env_release", 5.0f},
            {"env_filter_mod", 30.0f},
            {"lfo_speed", 0.2f},
            {"lfo_depth", 30.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 18.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Crystal Bell";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 0.0f},
            {"osc_tune", 8.0f},
            {"osc_detune", 2.0f},
            {"filter_cutoff", 7500.0f},
            {"filter_resonance", 0.6f},
            {"filter_mode", 2.0f},
            {"env_attack", 0.05f},
            {"env_decay", 0.8f},
            {"env_sustain", 0.5f},
            {"env_release", 3.5f},
            {"env_filter_mod", 30.0f},
            {"lfo_speed", 0.5f},
            {"lfo_depth", 40.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 1.0f},
            {"osc2_mix_depth", 65.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 1.5f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 2.5f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Sparkling Sunrise";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 6.0f},
            {"osc_detune", 5.0f},
            {"filter_cutoff", 8000.0f},
            {"filter_resonance", 0.4f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.2f},
            {"env_decay", 1.0f},
            {"env_sustain", 0.7f},
            {"env_release", 3.5f},
            {"env_filter_mod", 20.0f},
            {"lfo_speed", 0.4f},
            {"lfo_depth", 45.0f},
            {"lfo_target", 2.0f},
            {"output_gain", 0.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 3.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 15.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 9000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Luminous Pad";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", 4.0f},
            {"osc_detune", 7.0f},
            {"filter_cutoff", 7000.0f},
            {"filter_resonance", 0.3f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.4f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.8f},
            {"env_release", 4.5f},
            {"env_filter_mod", 15.0f},
            {"lfo_speed", 0.35f},
            {"lfo_depth", 35.0f},
            {"lfo_target", 1.0f},
            {"output_gain", 0.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 15.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Prismatic Glow";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 3.0f},
            {"osc_detune", 10.0f},
            {"filter_cutoff", 6500.0f},
            {"filter_resonance", 0.5f},
            {"filter_mode", 1.0f},
            {"env_attack", 0.3f},
            {"env_decay", 1.2f},
            {"env_sustain", 0.75f},
            {"env_release", 4.0f},
            {"env_filter_mod", 25.0f},
            {"lfo_speed", 0.45f},
            {"lfo_depth", 50.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -1.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 3.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 12.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 10000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Morphing Landscape";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", -4.0f},
            {"osc_detune", 20.0f},
            {"filter_cutoff", 4000.0f},
            {"filter_resonance", 0.35f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.0f},
            {"env_decay", 2.5f},
            {"env_sustain", 0.7f},
            {"env_release", 5.5f},
            {"env_filter_mod", 60.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 50.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 28.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 3000.0f},
            {"osc2_flt_reso", 0.2f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.5f},
            {"osc2_fenv_dec", 2.0f},
            {"osc2_fenv_sus", 0.4f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 50.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Breathing Pulse";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 6.0f},
            {"filter_cutoff", 4500.0f},
            {"filter_resonance", 0.3f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.6f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.7f},
            {"env_release", 4.0f},
            {"env_filter_mod", 35.0f},
            {"lfo_speed", 0.5f},
            {"lfo_depth", 60.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 90.0f},
            {"osc2_mix_mode", 1.0f},
            {"osc2_mix_depth", 45.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Spiraling Cosmos";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", -10.0f},
            {"osc_detune", 25.0f},
            {"filter_cutoff", 3500.0f},
            {"filter_resonance", 0.2f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.2f},
            {"env_decay", 3.0f},
            {"env_sustain", 0.65f},
            {"env_release", 6.0f},
            {"env_filter_mod", 40.0f},
            {"lfo_speed", 0.15f},
            {"lfo_depth", 45.0f},
            {"lfo_target", 2.0f},
            {"output_gain", -1.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 180.0f},
            {"osc2_mix_mode", 3.0f},
            {"osc2_mix_depth", 100.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.25f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Vintage Synth Pad";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 3.0f},
            {"osc_tune", -12.0f},
            {"osc_detune", 0.0f},
            {"filter_cutoff", 3000.0f},
            {"filter_resonance", 0.7f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.2f},
            {"env_decay", 1.2f},
            {"env_sustain", 0.75f},
            {"env_release", 3.5f},
            {"env_filter_mod", 50.0f},
            {"lfo_speed", 0.6f},
            {"lfo_depth", 55.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -4.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 35.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Blade Runner Night";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 8.0f},
            {"filter_cutoff", 1800.0f},
            {"filter_resonance", 0.55f},
            {"filter_mode", 0.0f},
            {"env_attack", 2.5f},
            {"env_decay", 2.0f},
            {"env_sustain", 0.65f},
            {"env_release", 7.0f},
            {"env_filter_mod", -20.0f},
            {"lfo_speed", 0.2f},
            {"lfo_depth", 22.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 22.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 800.0f},
            {"osc2_flt_reso", 0.15f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Alpha Centauri";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 14.0f},
            {"filter_cutoff", 5000.0f},
            {"filter_resonance", 0.35f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.8f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.85f},
            {"env_release", 8.0f},
            {"env_filter_mod", 30.0f},
            {"lfo_speed", 0.28f},
            {"lfo_depth", 28.0f},
            {"lfo_target", 2.0f},
            {"output_gain", -2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 0.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 30.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "CS80 Strings";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 18.0f},
            {"filter_cutoff", 4000.0f},
            {"filter_resonance", 0.45f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.7f},
            {"env_decay", 2.0f},
            {"env_sustain", 0.88f},
            {"env_release", 6.0f},
            {"env_filter_mod", 25.0f},
            {"lfo_speed", 0.22f},
            {"lfo_depth", 38.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 120.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 42.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Epic Cinema";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 10.0f},
            {"filter_cutoff", 7000.0f},
            {"filter_resonance", 0.2f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.2f},
            {"env_decay", 1.5f},
            {"env_sustain", 0.9f},
            {"env_release", 7.0f},
            {"env_filter_mod", 40.0f},
            {"lfo_speed", 0.2f},
            {"lfo_depth", 22.0f},
            {"lfo_target", 2.0f},
            {"output_gain", -1.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 3.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 18.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 8000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "String Machine";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 6.0f},
            {"filter_cutoff", 5500.0f},
            {"filter_resonance", 0.18f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.35f},
            {"env_decay", 0.8f},
            {"env_sustain", 0.92f},
            {"env_release", 3.5f},
            {"env_filter_mod", 12.0f},
            {"lfo_speed", 0.32f},
            {"lfo_depth", 20.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 38.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Oceanic Sweep";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 12.0f},
            {"filter_cutoff", 3000.0f},
            {"filter_resonance", 0.5f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.5f},
            {"env_decay", 2.0f},
            {"env_sustain", 0.8f},
            {"env_release", 6.0f},
            {"env_filter_mod", 25.0f},
            {"lfo_speed", 0.2f},
            {"lfo_depth", 70.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 90.0f},
            {"osc2_mix_mode", 1.0f},
            {"osc2_mix_depth", 45.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Cosmic Horizon";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 15.0f},
            {"filter_cutoff", 2800.0f},
            {"filter_resonance", 0.5f},
            {"filter_mode", 1.0f},
            {"env_attack", 2.5f},
            {"env_decay", 2.5f},
            {"env_sustain", 0.7f},
            {"env_release", 9.0f},
            {"env_filter_mod", 15.0f},
            {"lfo_speed", 0.15f},
            {"lfo_depth", 55.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 18.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 2.5f},
            {"osc2_env_decay", 3.0f},
            {"osc2_env_sustain", 0.4f},
            {"osc2_env_release", 6.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.0f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Electric Night";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", -12.0f},
            {"osc_detune", 10.0f},
            {"filter_cutoff", 3000.0f},
            {"filter_resonance", 0.5f},
            {"filter_mode", 0.0f},
            {"env_attack", 1.8f},
            {"env_decay", 2.5f},
            {"env_sustain", 0.75f},
            {"env_release", 8.0f},
            {"env_filter_mod", -25.0f},
            {"lfo_speed", 0.38f},
            {"lfo_depth", 28.0f},
            {"lfo_target", 1.0f},
            {"output_gain", 1.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 2.0f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 3.0f},
            {"fenv_sustain_on", 1.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 3.0f},
            {"osc2_mix_depth", 100.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.1f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.8f},
            {"osc2_env_release", 3.0f},
            {"osc2_env_sus_on", 1.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 2500.0f},
            {"osc2_flt_reso", 0.3f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "Laser Harp";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 6.0f},
            {"filter_cutoff", 900.0f},
            {"filter_resonance", 0.55f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.001f},
            {"env_decay", 0.4f},
            {"env_sustain", 0.75f},
            {"env_release", 5.0f},
            {"env_filter_mod", 80.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 0.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -5.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.4f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 1.0f},
            {"osc2_mix_depth", 70.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.15f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 1.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 3000.0f},
            {"osc2_flt_reso", 0.25f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 3.0f},
            {"osc2_fenv_sus_on", 1.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Fantasia";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 6.0f},
            {"filter_cutoff", 3500.0f},
            {"filter_resonance", 0.25f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.001f},
            {"env_decay", 0.4f},
            {"env_sustain", 0.06f},
            {"env_release", 5.5f},
            {"env_filter_mod", 65.0f},
            {"lfo_speed", 0.4f},
            {"lfo_depth", 12.0f},
            {"lfo_target", 1.0f},
            {"output_gain", 0.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.2f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 40.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.25f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 1.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Crystal";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 0.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 2.0f},
            {"filter_cutoff", 6000.0f},
            {"filter_resonance", 0.5f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.001f},
            {"env_decay", 0.5f},
            {"env_sustain", 0.06f},
            {"env_release", 7.0f},
            {"env_filter_mod", 70.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 35.0f},
            {"lfo_target", 0.0f},
            {"output_gain", 0.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.25f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 60.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.35f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 1.5f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Atmosphere";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 10.0f},
            {"filter_cutoff", 1800.0f},
            {"filter_resonance", 0.65f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.03f},
            {"env_decay", 0.7f},
            {"env_sustain", 0.06f},
            {"env_release", 7.0f},
            {"env_filter_mod", 80.0f},
            {"lfo_speed", 0.5f},
            {"lfo_depth", 12.0f},
            {"lfo_target", 1.0f},
            {"output_gain", -2.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.4f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 22.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.45f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 2.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 500.0f},
            {"osc2_flt_reso", 0.15f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Brightness";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 4.0f},
            {"filter_cutoff", 7000.0f},
            {"filter_resonance", 0.3f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.001f},
            {"env_decay", 0.35f},
            {"env_sustain", 0.07f},
            {"env_release", 4.5f},
            {"env_filter_mod", 40.0f},
            {"lfo_speed", 0.8f},
            {"lfo_depth", 55.0f},
            {"lfo_target", 0.0f},
            {"output_gain", 0.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.2f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 1.5f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 30.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.2f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 1.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Echoes";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 0.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 1.0f},
            {"filter_cutoff", 5000.0f},
            {"filter_resonance", 0.65f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.001f},
            {"env_decay", 0.8f},
            {"env_sustain", 0.05f},
            {"env_release", 8.0f},
            {"env_filter_mod", 65.0f},
            {"lfo_speed", 0.3f},
            {"lfo_depth", 25.0f},
            {"lfo_target", 1.0f},
            {"output_gain", 0.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.4f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 0.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 3.0f},
            {"osc2_mix_depth", 100.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 2.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Sci-Fi";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 3.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 5.0f},
            {"filter_cutoff", 2800.0f},
            {"filter_resonance", 0.55f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.001f},
            {"env_decay", 0.4f},
            {"env_sustain", 0.07f},
            {"env_release", 6.0f},
            {"env_filter_mod", 90.0f},
            {"lfo_speed", 0.4f},
            {"lfo_depth", 18.0f},
            {"lfo_target", 2.0f},
            {"output_gain", -1.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.35f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 35.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.3f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 1.5f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Voice";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 1.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 12.0f},
            {"filter_cutoff", 4500.0f},
            {"filter_resonance", 0.25f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.04f},
            {"env_decay", 0.6f},
            {"env_sustain", 0.08f},
            {"env_release", 5.0f},
            {"env_filter_mod", 40.0f},
            {"lfo_speed", 0.5f},
            {"lfo_depth", 25.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.45f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 1.0f},
            {"osc2_mix_depth", 40.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.5f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 2.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 1.0f},
            {"osc2_flt_cutoff", 4500.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "GM Strings";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 10.0f},
            {"filter_cutoff", 4500.0f},
            {"filter_resonance", 0.35f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.005f},
            {"env_decay", 0.45f},
            {"env_sustain", 0.1f},
            {"env_release", 5.5f},
            {"env_filter_mod", 35.0f},
            {"lfo_speed", 0.6f},
            {"lfo_depth", 22.0f},
            {"lfo_target", 2.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.005f},
            {"fenv_decay", 0.3f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 2.0f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 1.0f},
            {"osc2_mult", 1.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 0.0f},
            {"osc2_mix_depth", 30.0f},
            {"osc2_env_on", 0.0f},
            {"osc2_env_attack", 0.005f},
            {"osc2_env_decay", 0.4f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 2.0f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 1.0f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 2.0f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    {
        Preset p;
        p.name = "DX Bass 1";
        p.pluginId = "com.spellbound.arcanist";
        p.schemaVersion = 1;
        p.parameters = {
            {"osc_waveform", 2.0f},
            {"osc_tune", 0.0f},
            {"osc_detune", 3.0f},
            {"filter_cutoff", 1400.0f},
            {"filter_resonance", 0.25f},
            {"filter_mode", 0.0f},
            {"env_attack", 0.001f},
            {"env_decay", 0.07f},
            {"env_sustain", 0.45f},
            {"env_release", 0.4f},
            {"env_filter_mod", 55.0f},
            {"lfo_speed", 0.5f},
            {"lfo_depth", 0.0f},
            {"lfo_target", 0.0f},
            {"output_gain", -3.0f},
            {"env_sustain_on", 1.0f},
            {"fenv_attack", 0.001f},
            {"fenv_decay", 0.07f},
            {"fenv_sustain", 0.0f},
            {"fenv_release", 0.5f},
            {"fenv_sustain_on", 0.0f},
            {"osc2_on", 1.0f},
            {"osc2_waveform", 2.0f},
            {"osc2_mult", 2.0f},
            {"osc2_phase", 0.0f},
            {"osc2_mix_mode", 2.0f},
            {"osc2_mix_depth", 19.0f},
            {"osc2_env_on", 1.0f},
            {"osc2_env_attack", 0.001f},
            {"osc2_env_decay", 0.07f},
            {"osc2_env_sustain", 0.0f},
            {"osc2_env_release", 0.2f},
            {"osc2_env_sus_on", 0.0f},
            {"osc2_flt_on", 0.0f},
            {"osc2_flt_cutoff", 4000.0f},
            {"osc2_flt_reso", 0.1f},
            {"osc2_flt_mode", 0.0f},
            {"osc2_fenv_atk", 0.001f},
            {"osc2_fenv_dec", 0.5f},
            {"osc2_fenv_sus", 0.0f},
            {"osc2_fenv_rel", 0.5f},
            {"osc2_fenv_sus_on", 0.0f},
            {"osc2_fenv_depth", 0.0f},
        };
        presets.push_back(std::move(p));
    }
    return presets;
}
